import { useEffect, useMemo, useState } from 'react'
import { TeamAvatar } from './TeamAvatar'
import { standingsMobileTeamName } from './teamNameUtils.js'
import { fetchLeagueDataJson } from './leagueDataFetch.js'
import './WeeklyRecap.css'

/**
 * Weekly recap + pre-match look-forward. After each finished gameweek: an
 * odds-vs-reality strip, superlatives, then one card per fixture. Before
 * kick-off (and as a toggle on past weeks): win odds, why the model fancies
 * who to watch, recent waivers, last-week form, and bookie prices. GW selector +
 * pre/post toggle; generated by scripts/build-weekly-recaps.mjs.
 */
export function WeeklyRecap({ teamLogoMap = {}, kitIndexByEntry }) {
  const [data, setData] = useState(null)
  const [failed, setFailed] = useState(false)
  const [selectedGw, setSelectedGw] = useState(null)
  const [requestedMode, setRequestedMode] = useState(null)

  useEffect(() => {
    let alive = true
    fetchLeagueDataJson('weekly-recaps.json')
      .then((json) => {
        if (alive) setData(json)
      })
      .catch(() => {
        if (alive) setFailed(true)
      })
    return () => {
      alive = false
    }
  }, [])

  const options = useMemo(() => mergeRecapOptions(data), [data])
  const active = useMemo(() => {
    if (options.length === 0) return null
    const wanted = selectedGw ?? options[options.length - 1].gw
    return options.find((g) => g.gw === wanted) ?? options[options.length - 1]
  }, [options, selectedGw])

  const mode = useMemo(() => {
    if (!active) return 'recap'
    if (requestedMode === 'preview' && active.preview) return 'preview'
    if (requestedMode === 'recap' && active.recap) return 'recap'
    if (active.preview && !active.recap) return 'preview'
    if (active.recap && !active.preview) return 'recap'
    return 'recap'
  }, [active, requestedMode])

  if (failed) {
    return (
      <section className="tile tile--compact" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__note">Recaps unavailable right now.</p>
      </section>
    )
  }
  if (!data) {
    return (
      <section className="tile tile--compact" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__note">Loading…</p>
      </section>
    )
  }

  if (options.length === 0) {
    return (
      <section className="tile tile--compact weekly-recap" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__empty">
          The first look-forward drops once GW1 fixtures are up — every matchup
          gets the model&apos;s odds, who to watch, and what the underdog needs.
        </p>
        <p className="weekly-recap__note">
          Until then, the Predictions tab has the model&apos;s pre-season view.
        </p>
      </section>
    )
  }

  const recapGw = active.recap
  const previewGw = active.preview
  const showingPreview = mode === 'preview' && previewGw
  const heading = showingPreview ? `GW${active.gw} preview` : `GW${active.gw} recap`
  const decided = recapGw ? recapGw.model.hits + recapGw.model.misses : 0

  return (
    <>
      <section
        className="tile tile--compact weekly-recap"
        aria-labelledby="weekly-recap-heading"
      >
        <div className="tile-head-row tile-head-row--tight weekly-recap__head">
          <h2 id="weekly-recap-heading" className="tile-title tile-title--sm">
            {heading}
          </h2>
          <div className="weekly-recap__controls">
            <div
              className="weekly-recap__mode"
              role="group"
              aria-label="Pre-match or post-match"
            >
              <button
                type="button"
                className={
                  'weekly-recap__mode-btn' +
                  (showingPreview ? ' weekly-recap__mode-btn--active' : '')
                }
                aria-pressed={showingPreview}
                disabled={!previewGw}
                title={previewGw ? 'Model look-forward' : 'No pre-match preview for this week'}
                onClick={() => setRequestedMode('preview')}
              >
                Pre-match
              </button>
              <button
                type="button"
                className={
                  'weekly-recap__mode-btn' +
                  (!showingPreview ? ' weekly-recap__mode-btn--active' : '')
                }
                aria-pressed={!showingPreview}
                disabled={!recapGw}
                title={recapGw ? 'After the gameweek' : 'Recap drops when the gameweek finishes'}
                onClick={() => setRequestedMode('recap')}
              >
                Post-match
              </button>
            </div>
            {options.length > 1 ? (
              <label className="weekly-recap__select-wrap">
                <span className="visually-hidden">Choose gameweek</span>
                <select
                  className="weekly-recap__select"
                  value={active.gw}
                  onChange={(e) => setSelectedGw(Number(e.target.value))}
                >
                  {[...options].reverse().map((g) => (
                    <option key={g.gw} value={g.gw}>
                      GW{g.gw}
                      {g.recap ? '' : ' preview'}
                    </option>
                  ))}
                </select>
              </label>
            ) : null}
          </div>
        </div>

        {showingPreview ? (
          <PreviewHeader preview={previewGw} />
        ) : recapGw ? (
          <RecapHeader recapGw={recapGw} decided={decided} />
        ) : null}
      </section>

      {showingPreview
        ? previewGw.matchups.map((m) => (
            <PreviewMatchupCard
              key={`${m.home.entryId}-${m.away.entryId}`}
              matchup={m}
              teamLogoMap={teamLogoMap}
              kitIndexByEntry={kitIndexByEntry}
            />
          ))
        : recapGw
          ? recapGw.matchups.map((m) => (
              <MatchupCard
                key={`${m.home.entryId}-${m.away.entryId}`}
                matchup={m}
                teamLogoMap={teamLogoMap}
                kitIndexByEntry={kitIndexByEntry}
              />
            ))
          : null}
    </>
  )
}

function mergeRecapOptions(data) {
  if (!data) return []
  const recapByGw = new Map((data.gameweeks ?? []).map((g) => [g.gw, g]))
  const previewByGw = new Map((data.previews ?? []).map((g) => [g.gw, g]))
  const gws = new Set([...recapByGw.keys(), ...previewByGw.keys()])
  return [...gws]
    .sort((a, b) => a - b)
    .map((gw) => ({
      gw,
      recap: recapByGw.get(gw) ?? null,
      preview: previewByGw.get(gw) ?? null,
    }))
}

function RecapHeader({ recapGw, decided }) {
  return (
    <>
      <div className="weekly-recap__superlatives">
        {recapGw.superlatives.weekHigh ? (
          <span className="weekly-recap__superlative">
            <span className="weekly-recap__superlative-label">Week high</span>
            <span className="weekly-recap__superlative-value">
              {standingsMobileTeamName(recapGw.superlatives.weekHigh.name)} ·{' '}
              <span className="tabular">{recapGw.superlatives.weekHigh.points}</span>
            </span>
          </span>
        ) : null}
        {recapGw.superlatives.closest ? (
          <span className="weekly-recap__superlative">
            <span className="weekly-recap__superlative-label">Closest</span>
            <span className="weekly-recap__superlative-value">
              {standingsMobileTeamName(recapGw.superlatives.closest.homeName)} v{' '}
              {standingsMobileTeamName(recapGw.superlatives.closest.awayName)} (
              <span className="tabular">±{recapGw.superlatives.closest.margin}</span>)
            </span>
          </span>
        ) : null}
        {recapGw.superlatives.starPlayer ? (
          <span className="weekly-recap__superlative">
            <span className="weekly-recap__superlative-label">Star player</span>
            <span className="weekly-recap__superlative-value">
              {recapGw.superlatives.starPlayer.name} ·{' '}
              <span className="tabular">{recapGw.superlatives.starPlayer.pts}</span> (
              {standingsMobileTeamName(recapGw.superlatives.starPlayer.teamName)})
            </span>
          </span>
        ) : null}
        <WaiverChip waiver={recapGw.superlatives.bestWaiver} usePts />
        <DudChip dud={recapGw.superlatives.dud} usePts />
      </div>

      {decided > 0 || recapGw.model.draws > 0 ? (
        <div className="weekly-recap__odds" role="status">
          <div className="weekly-recap__odds-line">
            <span className="weekly-recap__odds-label">Odds accuracy</span>
            <span className="weekly-recap__odds-value tabular">
              {recapGw.model.hits} of {decided}
            </span>
            {recapGw.model.calls.length > 0 ? (
              <span className="weekly-recap__odds-dots" aria-hidden>
                {recapGw.model.calls.map((c, i) => (
                  <span
                    key={i}
                    className={
                      'weekly-recap__odds-dot' +
                      (c.outcome === 'hit'
                        ? ' weekly-recap__odds-dot--hit'
                        : c.outcome === 'miss'
                          ? ' weekly-recap__odds-dot--miss'
                          : ' weekly-recap__odds-dot--draw')
                    }
                    title={`${standingsMobileTeamName(c.favoriteName)} ${c.favoritePct}% — ${
                      c.outcome === 'hit'
                        ? 'called it'
                        : c.outcome === 'miss'
                          ? 'wrong'
                          : 'drawn'
                    }`}
                  />
                ))}
              </span>
            ) : null}
          </div>
          {recapGw.model.upset ? (
            <p className="weekly-recap__upset">
              Upset of the week:{' '}
              {standingsMobileTeamName(recapGw.model.upset.winnerName)} beat{' '}
              {standingsMobileTeamName(recapGw.model.upset.loserName)} with a{' '}
              <span className="tabular">{recapGw.model.upset.winnerPct}%</span>{' '}
              pre-match chance.
            </p>
          ) : null}
        </div>
      ) : null}
    </>
  )
}

function Superlative({ label, title, children }) {
  if (!children) return null
  return (
    <span className="weekly-recap__superlative" title={title}>
      <span className="weekly-recap__superlative-label">{label}</span>
      <span className="weekly-recap__superlative-value">{children}</span>
    </span>
  )
}

function teamHint(name) {
  return name ? ` (${standingsMobileTeamName(name)})` : ''
}

function WaiverChip({ waiver, usePts = false }) {
  if (!waiver?.name) return null
  const n = usePts ? waiver.pts : waiver.xp
  return (
    <Superlative
      label="Best waiver"
      title={
        usePts
          ? 'Recent claim who scored the most this week'
          : 'Recent claim with the highest projected points this week'
      }
    >
      {waiver.name}
      {Number.isFinite(n) ? (
        <>
          {' · '}
          <span className="tabular">{n}</span>
        </>
      ) : null}
      {teamHint(waiver.teamName)}
    </Superlative>
  )
}

function DudChip({ dud, usePts = false }) {
  if (!dud?.name) return null
  const n = usePts ? dud.pts : dud.xp
  return (
    <Superlative
      label="Dud"
      title={
        usePts
          ? 'Highest-drafted player with the fewest points this week'
          : 'Highest-drafted player with the lowest projected points this week'
      }
    >
      {dud.name}
      {Number.isFinite(dud.overallPick) ? (
        <>
          {' · pick '}
          <span className="tabular">{dud.overallPick}</span>
        </>
      ) : null}
      {Number.isFinite(n) ? (
        <>
          {' · '}
          <span className="tabular">{n}</span>
        </>
      ) : null}
      {teamHint(dud.teamName)}
    </Superlative>
  )
}

function PreviewHeader({ preview }) {
  const favourite = preview.superlatives?.favourite
  const closest = preview.superlatives?.closest
  const topScorer = preview.superlatives?.topScorer
  return (
    <>
      <p className="weekly-recap__note">
        What the model thinks before kick-off — odds, who to watch, and the
        underdog&apos;s path.
      </p>
      <div className="weekly-recap__superlatives">
        {favourite ? (
          <span className="weekly-recap__superlative">
            <span className="weekly-recap__superlative-label">Favourite</span>
            <span className="weekly-recap__superlative-value">
              {standingsMobileTeamName(favourite.name)} ·{' '}
              <span className="tabular">{favourite.pct}%</span>
            </span>
          </span>
        ) : null}
        {closest ? (
          <span className="weekly-recap__superlative">
            <span className="weekly-recap__superlative-label">Closest</span>
            <span className="weekly-recap__superlative-value">
              {standingsMobileTeamName(closest.homeName)} v{' '}
              {standingsMobileTeamName(closest.awayName)} (
              <span className="tabular">{closest.favoritePct}%</span>)
            </span>
          </span>
        ) : null}
        {topScorer ? (
          <Superlative label="Top scorer" title="Highest player score last week">
            {topScorer.name} · <span className="tabular">{topScorer.pts}</span>
            {teamHint(topScorer.teamName)}
          </Superlative>
        ) : null}
        <WaiverChip waiver={preview.superlatives?.bestWaiver} />
        <DudChip dud={preview.superlatives?.dud} />
      </div>
    </>
  )
}
  )
}

function MatchupCard({ matchup: m, teamLogoMap, kitIndexByEntry }) {
  const homeWon = m.winner === m.home.entryId
  const awayWon = m.winner === m.away.entryId
  return (
    <section
      className="tile tile--compact weekly-recap-matchup"
      aria-label={`${m.home.name} v ${m.away.name}`}
    >
      <div className="weekly-recap-matchup__scoreline">
        <span
          className={
            'weekly-recap-matchup__side weekly-recap-matchup__side--home' +
            (homeWon ? ' weekly-recap-matchup__side--won' : '')
          }
        >
          <span className="weekly-recap-matchup__side-label">
            <span className="weekly-recap-matchup__side-name">{m.home.name}</span>
            {m.home.manager ? (
              <span className="weekly-recap-matchup__side-mgr">{m.home.manager}</span>
            ) : null}
          </span>
          <TeamAvatar
            entryId={m.home.entryId}
            name={m.home.name}
            size="md"
            logoMap={teamLogoMap}
            kitIndexByEntry={kitIndexByEntry}
          />
        </span>
        <span className="weekly-recap-matchup__score tabular">
          {m.home.points}–{m.away.points}
        </span>
        <span
          className={
            'weekly-recap-matchup__side' +
            (awayWon ? ' weekly-recap-matchup__side--won' : '')
          }
        >
          <TeamAvatar
            entryId={m.away.entryId}
            name={m.away.name}
            size="md"
            logoMap={teamLogoMap}
            kitIndexByEntry={kitIndexByEntry}
          />
          <span className="weekly-recap-matchup__side-label">
            <span className="weekly-recap-matchup__side-name">{m.away.name}</span>
            {m.away.manager ? (
              <span className="weekly-recap-matchup__side-mgr">{m.away.manager}</span>
            ) : null}
          </span>
        </span>
      </div>

      {m.odds ? (
        <p className="weekly-recap-matchup__precall">
          Pre-match:{' '}
          {standingsMobileTeamName(
            m.odds.favoriteSide === 'home' ? m.home.name : m.away.name,
          )}{' '}
          <span className="tabular">{Math.round(m.odds.favoritePct)}%</span>
          {m.predicted ? (
            <>
              {' '}
              · points call{' '}
              <span className="tabular">
                {Math.round(m.predicted.home)}–{Math.round(m.predicted.away)}
              </span>
            </>
          ) : null}
          <span
            className={
              'weekly-recap-matchup__outcome-dot' +
              (m.odds.outcome === 'hit'
                ? ' weekly-recap-matchup__outcome-dot--hit'
                : m.odds.outcome === 'miss'
                  ? ' weekly-recap-matchup__outcome-dot--miss'
                  : ' weekly-recap-matchup__outcome-dot--draw')
            }
            title={
              m.odds.outcome === 'hit'
                ? 'Model called it'
                : m.odds.outcome === 'miss'
                  ? 'Model missed'
                  : 'Drawn'
            }
            aria-hidden
          />
          <span className="visually-hidden">
            {m.odds.outcome === 'hit'
              ? 'Model called it'
              : m.odds.outcome === 'miss'
                ? 'Model missed'
                : 'Drawn'}
          </span>
        </p>
      ) : null}

      <p className="weekly-recap-matchup__prose">{m.sentences.join(' ')}</p>

      <TeamMetaRows
        home={m.home}
        away={m.away}
        teamLogoMap={teamLogoMap}
        kitIndexByEntry={kitIndexByEntry}
        showResultMeta
      />
    </section>
  )
}

function PreviewMatchupCard({ matchup: m, teamLogoMap, kitIndexByEntry }) {
  const homeFav = m.odds?.favoriteSide === 'home'
  const awayFav = m.odds?.favoriteSide === 'away'
  return (
    <section
      className="tile tile--compact weekly-recap-matchup weekly-recap-matchup--preview"
      aria-label={`${m.home.name} v ${m.away.name} preview`}
    >
      <div className="weekly-recap-matchup__scoreline">
        <span
          className={
            'weekly-recap-matchup__side weekly-recap-matchup__side--home' +
            (homeFav ? ' weekly-recap-matchup__side--won' : '')
          }
        >
          <span className="weekly-recap-matchup__side-label">
            <span className="weekly-recap-matchup__side-name">{m.home.name}</span>
            {m.home.manager ? (
              <span className="weekly-recap-matchup__side-mgr">{m.home.manager}</span>
            ) : null}
          </span>
          <TeamAvatar
            entryId={m.home.entryId}
            name={m.home.name}
            size="md"
            logoMap={teamLogoMap}
            kitIndexByEntry={kitIndexByEntry}
          />
        </span>
        <span className="weekly-recap-matchup__odds-triple" aria-label="Win odds">
          <span
            className={
              'weekly-recap-matchup__odds-leg tabular' +
              (homeFav ? ' weekly-recap-matchup__odds-leg--fav' : '')
            }
          >
            {m.odds?.home ?? '–'}
            <span className="weekly-recap-matchup__odds-pct">%</span>
          </span>
          <span className="weekly-recap-matchup__odds-leg weekly-recap-matchup__odds-leg--draw tabular">
            {m.odds?.draw ?? '–'}
            <span className="weekly-recap-matchup__odds-pct">%</span>
          </span>
          <span
            className={
              'weekly-recap-matchup__odds-leg tabular' +
              (awayFav ? ' weekly-recap-matchup__odds-leg--fav' : '')
            }
          >
            {m.odds?.away ?? '–'}
            <span className="weekly-recap-matchup__odds-pct">%</span>
          </span>
        </span>
        <span
          className={
            'weekly-recap-matchup__side' +
            (awayFav ? ' weekly-recap-matchup__side--won' : '')
          }
        >
          <TeamAvatar
            entryId={m.away.entryId}
            name={m.away.name}
            size="md"
            logoMap={teamLogoMap}
            kitIndexByEntry={kitIndexByEntry}
          />
          <span className="weekly-recap-matchup__side-label">
            <span className="weekly-recap-matchup__side-name">{m.away.name}</span>
            {m.away.manager ? (
              <span className="weekly-recap-matchup__side-mgr">{m.away.manager}</span>
            ) : null}
          </span>
        </span>
      </div>

      {m.odds ? (
        <p className="weekly-recap-matchup__precall">
          Book:{' '}
          <span className="tabular">{m.bookie?.home ?? '–'}</span>
          {' · '}
          <span className="tabular">{m.bookie?.draw ?? '–'}</span>
          {' · '}
          <span className="tabular">{m.bookie?.away ?? '–'}</span>
        </p>
      ) : null}

      <p className="weekly-recap-matchup__prose">{m.sentences.join(' ')}</p>

      <TeamMetaRows
        home={m.home}
        away={m.away}
        teamLogoMap={teamLogoMap}
        kitIndexByEntry={kitIndexByEntry}
        showResultMeta={false}
      />
    </section>
  )
}

function TeamMetaRows({ home, away, teamLogoMap, kitIndexByEntry, showResultMeta }) {
  return (
    <div className="weekly-recap-matchup__teams">
      {[home, away].map((t) => (
        <div key={t.entryId} className="weekly-recap-matchup__team-row">
          <TeamAvatar
            entryId={t.entryId}
            name={t.name}
            size="sm"
            logoMap={teamLogoMap}
            kitIndexByEntry={kitIndexByEntry}
          />
          <span className="weekly-recap-matchup__team-id">
            <span className="weekly-recap-matchup__team-id-top">
              <span className="weekly-recap-matchup__team-name">
                {standingsMobileTeamName(t.name)}
              </span>
              {showResultMeta && t.streak && t.streak.len >= 2 ? (
                <span
                  className={
                    'weekly-recap-matchup__streak' +
                    (t.streak.type === 'W'
                      ? ' weekly-recap-matchup__streak--w'
                      : t.streak.type === 'L'
                        ? ' weekly-recap-matchup__streak--l'
                        : '')
                  }
                  title={`${t.streak.len} ${t.streak.type === 'W' ? 'wins' : t.streak.type === 'L' ? 'defeats' : 'draws'} in a row`}
                >
                  {t.streak.type}
                  {t.streak.len}
                </span>
              ) : null}
            </span>
            {t.manager ? (
              <span className="weekly-recap-matchup__team-mgr">{t.manager}</span>
            ) : null}
          </span>
          <span className="weekly-recap-matchup__team-rank tabular">
            {t.rank != null ? ordinal(t.rank) : '–'}
            {showResultMeta && t.prevRank != null && t.prevRank !== t.rank ? (
              <span
                className={
                  'weekly-recap-matchup__rank-move ' +
                  (t.rank < t.prevRank
                    ? 'weekly-recap-matchup__rank-move--up'
                    : 'weekly-recap-matchup__rank-move--down')
                }
                aria-label={
                  t.rank < t.prevRank
                    ? `up from ${ordinal(t.prevRank)}`
                    : `down from ${ordinal(t.prevRank)}`
                }
              >
                {t.rank < t.prevRank ? '▲' : '▼'}
              </span>
            ) : null}
          </span>
          <span className="weekly-recap-matchup__team-record tabular">
            {t.record ? `${t.record.w}-${t.record.d}-${t.record.l}` : '–'}
          </span>
          {showResultMeta && t.players?.top ? (
            <span
              className="weekly-recap-matchup__team-top"
              title={`Top scorer: ${t.players.top.name} (${t.players.top.pts})`}
            >
              ★ {t.players.top.name}{' '}
              <span className="tabular">{t.players.top.pts}</span>
            </span>
          ) : t.keys?.[0] ? (
            <span
              className="weekly-recap-matchup__team-top"
              title={`Watch: ${t.keys[0].name} (${t.keys[0].xp})`}
            >
              ★ {t.keys[0].name}{' '}
              <span className="tabular">{t.keys[0].xp}</span>
            </span>
          ) : null}
          {showResultMeta && t.titleOdds ? (
            <span className="weekly-recap-matchup__team-odds tabular">
              title {t.titleOdds.before}% → {t.titleOdds.after}%
            </span>
          ) : Number.isFinite(t.titlePct) ? (
            <span className="weekly-recap-matchup__team-odds tabular">
              title {t.titlePct}%
            </span>
          ) : null}
        </div>
      ))}
    </div>
  )
}

function ordinal(n) {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return `${n}${s[(v - 20) % 10] || s[v] || s[0]}`
}
