import { useEffect, useMemo, useState } from 'react'
import { fetchLeagueDataJson, fetchLeagueDataJsonOptional } from './leagueDataFetch.js'
import { indexRecapSite, padGw } from './recapSiteContext.js'
import {
  defaultRecapView,
  defaultModeForGw,
  recapMenuLabelForStatus,
  visibleRecapOptions,
  mergeRecapOptions,
} from './weeklyRecapView.js'
import { ScanHeader, ScanMatchups } from './WeeklyRecapScan.jsx'
import './WeeklyRecap.css'

async function loadRecapSiteData() {
  const [benchPoints, seasonPredictions, draftPicks, histIndex] = await Promise.all([
    fetchLeagueDataJsonOptional('bench-points.json'),
    fetchLeagueDataJsonOptional('season-predictions.json'),
    fetchLeagueDataJsonOptional('draft_picks.json'),
    fetchLeagueDataJsonOptional('projections-history/index.json'),
  ])
  const gws = Array.isArray(histIndex?.gameweeks) ? histIndex.gameweeks : []
  const pairs = await Promise.all(
    gws.map(async (gw) => {
      const json = await fetchLeagueDataJsonOptional(
        `projections-history/gw-${padGw(gw)}.json`,
      )
      return [Number(gw), json]
    }),
  )
  const historyByGw = {}
  for (const [gw, json] of pairs) {
    if (json) historyByGw[gw] = json
  }
  return { benchPoints, seasonPredictions, draftPicks, historyByGw }
}

/**
 * Weekly recap + pre-match look-forward. After each finished gameweek: an
 * odds-vs-reality strip, superlatives, then one card per fixture. Before
 * kick-off (and as a toggle on past weeks): win odds, why the model fancies
 * who to watch, recent waivers, last-week form, and bookie prices. GW selector +
 * Preview/Recap toggle; generated by scripts/build-weekly-recaps.mjs from locked XIs.
 *
 * Default: after the lineup deadline (live) opens Preview; looking back (GW
 * complete, or still before the next deadline) opens Recap. Copied-forward
 * XIs before the deadline are not a preview. The FPL Live menu label follows.
 */
export function WeeklyRecap({
  teamLogoMap = {},
  kitIndexByEntry,
  liveStatus = null,
  onMenuLabelChange,
  matches = [],
  leagueEntries = [],
}) {
  const [data, setData] = useState(null)
  const [siteRaw, setSiteRaw] = useState(null)
  const [failed, setFailed] = useState(false)
  const [selectedGw, setSelectedGw] = useState(null)
  const [requestedMode, setRequestedMode] = useState(null)

  useEffect(() => {
    let alive = true
    Promise.all([
      fetchLeagueDataJson('weekly-recaps.json'),
      loadRecapSiteData().catch(() => null),
    ])
      .then(([json, site]) => {
        if (!alive) return
        setData(json)
        setSiteRaw(site)
      })
      .catch(() => {
        if (alive) setFailed(true)
      })
    return () => {
      alive = false
    }
  }, [])

  const options = useMemo(
    () =>
      visibleRecapOptions(
        mergeRecapOptions(data, {
          matches,
          leagueEntries,
          lastFinishedGw: liveStatus?.lastFinishedGw,
        }),
        {
          upcomingGw: data?.upcomingGw,
          liveStatus: liveStatus?.status,
        },
      ),
    [data, liveStatus?.status, liveStatus?.lastFinishedGw, matches, leagueEntries],
  )
  const lastFinishedGw = useMemo(() => {
    const baked = Number(data?.lastFinishedGw)
    const live = Number(liveStatus?.lastFinishedGw)
    const fromOpts = options.filter((g) => g.recap).map((g) => Number(g.gw))
    return Math.max(
      0,
      Number.isFinite(baked) ? baked : 0,
      Number.isFinite(live) ? live : 0,
      fromOpts.length ? Math.max(...fromOpts) : 0,
    )
  }, [data?.lastFinishedGw, liveStatus?.lastFinishedGw, options])
  const fallback = useMemo(
    () =>
      defaultRecapView({
        lastFinishedGw: lastFinishedGw || null,
        upcomingGw: data?.upcomingGw,
        liveStatus: liveStatus?.status,
        options,
      }),
    [lastFinishedGw, data?.upcomingGw, liveStatus?.status, options],
  )
  const active = useMemo(() => {
    if (options.length === 0) return null
    const wanted = selectedGw ?? fallback.gw
    return options.find((g) => g.gw === wanted) ?? options[options.length - 1]
  }, [options, selectedGw, fallback.gw])

  const mode = useMemo(() => {
    if (!active) return fallback.mode
    if (requestedMode === 'preview' && active.preview) return 'preview'
    if (requestedMode === 'recap' && active.recap) return 'recap'
    if (selectedGw == null && active.gw === fallback.gw) return fallback.mode
    return defaultModeForGw(active)
  }, [active, requestedMode, selectedGw, fallback])

  const showingPreview = mode === 'preview' && Boolean(active?.preview)
  const menuLabel = !data
    ? recapMenuLabelForStatus(liveStatus?.status)
    : showingPreview
      ? 'Preview'
      : 'Recap'

  useEffect(() => {
    onMenuLabelChange?.(menuLabel)
  }, [menuLabel, onMenuLabelChange])

  const site = useMemo(
    () => indexRecapSite({ ...(siteRaw || {}), matches }),
    [siteRaw, matches],
  )

  if (failed) {
    return (
      <section className="tile tile--compact" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__note">Recaps unavailable right now.</p>
      </section>
    )
  }
  if (!data) {
    return (
      <section className="tile tile--compact" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">{menuLabel}</h2>
        <p className="weekly-recap__note">Loading…</p>
      </section>
    )
  }

  if (options.length === 0) {
    return (
      <section className="tile tile--compact weekly-recap" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__empty">
          The first look-forward drops once starting XIs are in — every matchup
          gets the week&apos;s odds, who to watch, and whether the bench looks off.
        </p>
        <p className="weekly-recap__note">
          Until then, the Predictions tab has the model&apos;s pre-season view.
        </p>
      </section>
    )
  }

  const recapGw = active.recap
  const previewGw = active.preview
  const heading = showingPreview ? `GW${active.gw} preview` : `GW${active.gw} recap`
  const decided = recapGw ? recapGw.model.hits + recapGw.model.misses : 0
  const priorGws = (data?.gameweeks || []).filter((g) => Number(g.gw) < Number(active.gw))

  return (
    <>
      <section
        className="tile tile--compact weekly-recap"
        aria-labelledby="weekly-recap-heading"
      >
        <div className="tile-head-row tile-head-row--tight weekly-recap__head">
          <h2 id="weekly-recap-heading" className="tile-title tile-title--sm">
            {heading}
          </h2>
          <div className="weekly-recap__controls">
            <div
              className="weekly-recap__mode"
              role="group"
              aria-label="Preview or recap"
            >
              <button
                type="button"
                className={
                  'weekly-recap__mode-btn' +
                  (showingPreview ? ' weekly-recap__mode-btn--active' : '')
                }
                aria-pressed={showingPreview}
                disabled={!previewGw}
                title={previewGw ? 'Look-forward from starting XIs' : 'No preview for this week'}
                onClick={() => setRequestedMode('preview')}
              >
                Preview
              </button>
              <button
                type="button"
                className={
                  'weekly-recap__mode-btn' +
                  (!showingPreview ? ' weekly-recap__mode-btn--active' : '')
                }
                aria-pressed={!showingPreview}
                disabled={!recapGw}
                title={recapGw ? 'After the gameweek' : 'Recap drops when the gameweek finishes'}
                onClick={() => setRequestedMode('recap')}
              >
                Recap
              </button>
            </div>
            {options.length > 1 ? (
              <label className="weekly-recap__select-wrap">
                <span className="visually-hidden">Choose gameweek</span>
                <select
                  className="weekly-recap__select"
                  value={active.gw}
                  onChange={(e) => {
                    setSelectedGw(Number(e.target.value))
                    setRequestedMode(null)
                  }}
                >
                  {[...options].reverse().map((g) => (
                    <option key={g.gw} value={g.gw}>
                      GW{g.gw}
                      {g.recap ? ' recap' : ' preview'}
                    </option>
                  ))}
                </select>
              </label>
            ) : null}
          </div>
        </div>

        <ScanHeader
          recapGw={recapGw}
          previewGw={previewGw}
          preview={showingPreview}
          decided={decided}
        />
      </section>

      <ScanMatchups
        matchups={
          showingPreview ? previewGw.matchups : recapGw ? recapGw.matchups : []
        }
        preview={showingPreview}
        priorGws={priorGws}
        site={site}
        teamLogoMap={teamLogoMap}
        kitIndexByEntry={kitIndexByEntry}
      />
    </>
  )
}
