import { useEffect, useMemo, useState } from 'react'
import { TeamAvatar } from './TeamAvatar'
import { standingsMobileTeamName } from './teamNameUtils.js'
import './WeeklyRecap.css'

/**
 * Weekly recap — after each finished gameweek, three sentences per team
 * (result / trend / model odds swing) plus the week's superlatives, all
 * generated by scripts/build-weekly-recaps.mjs. GW selector keeps every
 * past week readable.
 */
export function WeeklyRecap({ teamLogoMap = {}, kitIndexByEntry }) {
  const [data, setData] = useState(null)
  const [failed, setFailed] = useState(false)
  const [selectedGw, setSelectedGw] = useState(null)

  useEffect(() => {
    let alive = true
    fetch(`${import.meta.env.BASE_URL}league-data/weekly-recaps.json`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((json) => {
        if (alive) setData(json)
      })
      .catch(() => {
        if (alive) setFailed(true)
      })
    return () => {
      alive = false
    }
  }, [])

  const gameweeks = useMemo(() => data?.gameweeks ?? [], [data])
  const activeGw = useMemo(() => {
    if (gameweeks.length === 0) return null
    const wanted = selectedGw ?? gameweeks[gameweeks.length - 1].gw
    return gameweeks.find((g) => g.gw === wanted) ?? gameweeks[gameweeks.length - 1]
  }, [gameweeks, selectedGw])

  if (failed) {
    return (
      <section className="tile tile--compact" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__note">Recaps unavailable right now.</p>
      </section>
    )
  }
  if (!data) {
    return (
      <section className="tile tile--compact" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__note">Loading…</p>
      </section>
    )
  }

  if (gameweeks.length === 0) {
    return (
      <section className="tile tile--compact weekly-recap" aria-label="Weekly recap">
        <h2 className="tile-title tile-title--sm">Weekly recap</h2>
        <p className="weekly-recap__empty">
          The first recap drops when GW1 finishes — every gameweek gets a
          three-sentence read on all eight teams, plus how the title odds moved.
        </p>
        <p className="weekly-recap__note">
          Until then, the Predictions tab has the model's pre-season view.
        </p>
      </section>
    )
  }

  return (
    <>
      <section
        className="tile tile--compact weekly-recap"
        aria-labelledby="weekly-recap-heading"
      >
        <div className="tile-head-row tile-head-row--tight weekly-recap__head">
          <h2 id="weekly-recap-heading" className="tile-title tile-title--sm">
            GW{activeGw.gw} recap
          </h2>
          {gameweeks.length > 1 ? (
            <label className="weekly-recap__select-wrap">
              <span className="visually-hidden">Choose gameweek</span>
              <select
                className="weekly-recap__select"
                value={activeGw.gw}
                onChange={(e) => setSelectedGw(Number(e.target.value))}
              >
                {[...gameweeks].reverse().map((g) => (
                  <option key={g.gw} value={g.gw}>
                    GW{g.gw}
                  </option>
                ))}
              </select>
            </label>
          ) : null}
        </div>

        <div className="weekly-recap__superlatives">
          {activeGw.superlatives.weekHigh ? (
            <span className="weekly-recap__superlative">
              <span className="weekly-recap__superlative-label">Week high</span>
              <span className="weekly-recap__superlative-value">
                {standingsMobileTeamName(activeGw.superlatives.weekHigh.name)} ·{' '}
                <span className="tabular">{activeGw.superlatives.weekHigh.points}</span>
              </span>
            </span>
          ) : null}
          {activeGw.superlatives.closest ? (
            <span className="weekly-recap__superlative">
              <span className="weekly-recap__superlative-label">Closest</span>
              <span className="weekly-recap__superlative-value">
                {standingsMobileTeamName(activeGw.superlatives.closest.homeName)} v{' '}
                {standingsMobileTeamName(activeGw.superlatives.closest.awayName)} (
                <span className="tabular">±{activeGw.superlatives.closest.margin}</span>)
              </span>
            </span>
          ) : null}
        </div>

        <ul className="weekly-recap__results" aria-label={`GW${activeGw.gw} results`}>
          {activeGw.matches.map((m) => (
            <li key={`${m.home}-${m.away}`} className="weekly-recap__result">
              <span
                className={
                  'weekly-recap__result-team weekly-recap__result-team--home' +
                  (m.homePts > m.awayPts ? ' weekly-recap__result-team--won' : '')
                }
              >
                {standingsMobileTeamName(m.homeName)}
              </span>
              <span className="weekly-recap__result-score tabular">
                {m.homePts}–{m.awayPts}
              </span>
              <span
                className={
                  'weekly-recap__result-team' +
                  (m.awayPts > m.homePts ? ' weekly-recap__result-team--won' : '')
                }
              >
                {standingsMobileTeamName(m.awayName)}
              </span>
            </li>
          ))}
        </ul>
      </section>

      {activeGw.teams.map((t) => (
        <section
          key={t.entryId}
          className="tile tile--compact weekly-recap-card"
          aria-label={`${t.name} GW${activeGw.gw} recap`}
        >
          <div className="weekly-recap-card__head">
            <TeamAvatar
              entryId={t.entryId}
              name={t.name}
              size="md"
              logoMap={teamLogoMap}
              kitIndexByEntry={kitIndexByEntry}
            />
            <div className="weekly-recap-card__title">
              <h3 className="weekly-recap-card__name">
                {standingsMobileTeamName(t.name)}
              </h3>
              <span className="weekly-recap-card__sub">
                <span
                  className={`weekly-recap-card__result-chip weekly-recap-card__result-chip--${t.result.toLowerCase()}`}
                >
                  {t.result}
                </span>{' '}
                <span className="tabular">
                  {t.points}–{t.oppPoints}
                </span>{' '}
                v {standingsMobileTeamName(t.oppName)}
              </span>
            </div>
            <span className="weekly-recap-card__rank tabular" title="League position">
              {ordinal(t.rank)}
              {t.prevRank != null && t.prevRank !== t.rank ? (
                <span
                  className={
                    'weekly-recap-card__rank-move ' +
                    (t.rank < t.prevRank
                      ? 'weekly-recap-card__rank-move--up'
                      : 'weekly-recap-card__rank-move--down')
                  }
                  aria-label={
                    t.rank < t.prevRank
                      ? `up from ${ordinal(t.prevRank)}`
                      : `down from ${ordinal(t.prevRank)}`
                  }
                >
                  {t.rank < t.prevRank ? '▲' : '▼'}
                </span>
              ) : null}
            </span>
          </div>
          <p className="weekly-recap-card__prose">{t.sentences.join(' ')}</p>
          <dl className="weekly-recap-card__meta">
            <div className="weekly-recap-card__meta-item">
              <dt>Record</dt>
              <dd className="tabular">
                {t.record.w}-{t.record.d}-{t.record.l}
              </dd>
            </div>
            <div className="weekly-recap-card__meta-item">
              <dt>Season avg</dt>
              <dd className="tabular">{t.seasonAvg}</dd>
            </div>
            {t.titleOdds ? (
              <div className="weekly-recap-card__meta-item">
                <dt>Title odds</dt>
                <dd className="tabular">
                  {t.titleOdds.before}% → {t.titleOdds.after}%
                </dd>
              </div>
            ) : null}
          </dl>
        </section>
      ))}
    </>
  )
}

function ordinal(n) {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return `${n}${s[(v - 20) % 10] || s[v] || s[0]}`
}
